Description: >
  K8S cluster for the cloud-dash application

Parameters:
  ClusterName:
    Description: Name of the cluster
    Type: String

  KubernetesVersion:
    Default: "1.15"
    Description: K8S version for the cluster
    Type: String

  ClusterRoleArn:
    Description: ARN Role to assign to the cluster
    Type: String

  ClusterSubnets:
    Description: List of subnets where the cluster can spawn nodes
    Type: CommaDelimitedList

  ClusterNodeGroupRoleArn:
    Description: ARN Role to assign to the node group
    Type: String

Resources:
  cluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !Ref ClusterRoleArn
      ResourcesVpcConfig:
        SubnetIds: !Ref ClusterSubnets

  nodeGroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: !Ref cluster
      NodegroupName: !Sub "${ClusterName}-node-group"
      NodeRole: !Ref ClusterNodeGroupRoleArn
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      Subnets: !Ref ClusterSubnets
