Resources:
  cluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: covid-dash
      Version: "1.15"
      RoleArn: >-
        arn:aws:iam::835818189829:role/EKSTest
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-f7a4418f
          - subnet-55d92d08
          - subnet-48838403
          - subnet-acfc9087

  nodeGroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: !Ref cluster
      NodegroupName: covid-dash
      NodeRole: "arn:aws:iam::835818189829:role/TetsEks"
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      Subnets:
        - subnet-f7a4418f
        - subnet-55d92d08
        - subnet-48838403
        - subnet-acfc9087
