apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-dash
  labels:
    app: covid-dash
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: covid-dash
  template:
    metadata:
      labels:
        app: covid-dash
    spec:
      containers:
        - name: covid-dash
          image: paguos/covid-dash:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
