apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-dash
  labels:
    app: covid-dash
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: covid-dash
  template:
    metadata:
      labels:
        app: covid-dash
    spec:
      containers:
        - name: ml-k8s
          image: paguos/covid-dash:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
